// crates/fissio-editor/client/src/lib/components/Header.tsx
import { createMemo, For, Show } from 'solid-js';
import Settings from './Settings';
import type { ModelConfig, PipelineInfo } from '../types';

type Props = {
  isConnected: boolean;
  models: ModelConfig[];
  selectedModel: string;
  onModelChange: (id: string) => void;
  pipelines: PipelineInfo[];
  selectedPipeline: string;
  onPipelineChange: (id: string) => void;
  modelStatus: string;
  pipelineModified?: boolean;
  onEditPipeline?: () => void;
  onDeletePipeline?: (id: string) => void;
};

const STATUS_TEXT: Record<string, string> = {
  loading: 'Loading model...',
  unloading: 'Unloading model...'
};

export default function Header(props: Props) {
  const statusText = createMemo(() => STATUS_TEXT[props.modelStatus] ?? '');
  const currentPipeline = createMemo(() => props.pipelines.find(p => p.id === props.selectedPipeline));
  const selectorsDisabled = createMemo(() => !props.isConnected || !!statusText());

  return (
    <div class="header-container">
      <header>
        <div class="status" classList={{ connected: props.isConnected }} />
        <b>fissio</b>
        <Show when={statusText()}>
          <span class="model-status">{statusText()}</span>
        </Show>
        <div class="selectors" classList={{ 'no-status': !statusText() }}>
          <div class="pipeline-wrapper">
            <select
              class="pipeline-select"
              value={props.selectedPipeline}
              onChange={(e) => props.onPipelineChange(e.currentTarget.value)}
              disabled={selectorsDisabled()}
              title="Agent Config"
            >
              <option value="">Direct Chat</option>
              <For each={props.pipelines}>
                {(pipeline) => (
                  <option value={pipeline.id} title={pipeline.description}>{pipeline.name}</option>
                )}
              </For>
              <option value="__new__">-- Create agent --</option>
            </select>
            <Show when={currentPipeline()}>
              <button
                class="delete-btn"
                onClick={() => props.onDeletePipeline?.(props.selectedPipeline)}
                title="Delete config"
              >✕</button>
              <button
                class="edit-btn"
                classList={{ modified: props.pipelineModified }}
                onClick={() => props.onEditPipeline?.()}
                disabled={!props.isConnected}
                title="Edit pipeline"
              >
                ✎
              </button>
            </Show>
          </div>
          <select
            class="model-select"
            value={props.selectedModel}
            onChange={(e) => props.onModelChange(e.currentTarget.value)}
            disabled={selectorsDisabled()}
            title="Default Model"
          >
            <option value="none">-- Unload GPU --</option>
            <For each={props.models}>
              {(model) => <option value={model.id}>{model.name}</option>}
            </For>
          </select>
        </div>
        <a href="/observe" class="observe-btn" title="Observe">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
          </svg>
        </a>
        <Settings />
      </header>
    </div>
  );
}

// client/src/lib/components/Header.svelte
<script lang="ts">
	import Settings from './Settings.svelte';
	import type { ModelConfig, PipelineInfo } from '$lib/types';

	export let isConnected: boolean;
	export let models: ModelConfig[];
	export let selectedModel: string;
	export let pipelines: PipelineInfo[];
	export let selectedPipeline: string;
	export let modelStatus: string;
	export let pipelineModified: boolean = false;
	export let onEditPipeline: () => void = () => {};
	export let onDeletePipeline: (id: string) => void = () => {};

	$: statusText = modelStatus === 'loading' ? 'Loading model...' :
		modelStatus === 'unloading' ? 'Unloading model...' : '';

	$: currentPipeline = pipelines.find(p => p.id === selectedPipeline);
</script>

<div class="header-container">
	<header>
		<div class="status" class:connected={isConnected}></div>
		<b>agents-rs</b>
		{#if statusText}
			<span class="model-status">{statusText}</span>
		{/if}
		<div class="selectors" class:no-status={!statusText}>
			<div class="pipeline-wrapper">
				<select bind:value={selectedPipeline} class="pipeline-select" disabled={!isConnected || !!statusText} title="Agent Config">
					{#each pipelines as pipeline}
						<option value={pipeline.id} title={pipeline.description}>{pipeline.name}</option>
					{/each}
					<option value="__new__">-- Define agent... --</option>
				</select>
				{#if currentPipeline}
					<button
						class="delete-btn"
						onclick={() => onDeletePipeline(selectedPipeline)}
						title="Delete config"
					>✕</button>
				{/if}
				<button
					class="edit-btn"
					class:modified={pipelineModified}
					onclick={onEditPipeline}
					disabled={!isConnected || !currentPipeline}
					title="Edit pipeline"
				>
					✎
				</button>
			</div>
			<select bind:value={selectedModel} class="model-select" disabled={!isConnected || !!statusText} title="Default Model">
				<option value="none">-- Unload GPU --</option>
				{#each models as model}
					<option value={model.id}>{model.name}</option>
				{/each}
			</select>
		</div>
		<Settings />
	</header>
</div>

<style>
	.header-container {
		display: flex;
		flex-direction: column;
	}

	.model-status {
		margin-left: auto;
		font-size: 0.875rem;
		color: var(--text-secondary, #888);
		font-style: italic;
	}

	.selectors {
		display: flex;
		gap: 0.5rem;
		margin-left: 0.5rem;
	}

	.selectors.no-status {
		margin-left: auto;
	}

	.pipeline-wrapper {
		display: flex;
		gap: 0;
	}

	.pipeline-select,
	.model-select {
		padding: 0.25rem 0.5rem;
		border-radius: 4px;
		border: 1px solid var(--border);
		background: var(--bg-secondary);
		color: var(--text);
		font-size: 0.875rem;
		cursor: pointer;
	}

	.pipeline-select {
		border-top-right-radius: 0;
		border-bottom-right-radius: 0;
		border-right: none;
	}

	.edit-btn {
		padding: 0.25rem 0.5rem;
		border-radius: 0 4px 4px 0;
		border: 1px solid var(--border);
		background: var(--bg-secondary);
		color: var(--text);
		font-size: 0.875rem;
		cursor: pointer;
	}

	.edit-btn:hover:not(:disabled) {
		background: var(--accent, #3b82f6);
	}

	.edit-btn.modified {
		border-color: #f59e0b;
		color: #f59e0b;
	}

	.edit-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.delete-btn {
		padding: 0.25rem 0.4rem;
		border: 1px solid var(--border);
		border-left: none;
		border-radius: 0;
		background: var(--bg-secondary);
		color: #ef4444;
		font-size: 0.75rem;
		cursor: pointer;
	}

	.delete-btn:hover {
		background: #ef4444;
		color: white;
	}

	.pipeline-select:disabled,
	.model-select:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.status {
		width: 10px;
		height: 10px;
		border-radius: 50%;
		background: #ef4444;
		margin-right: 0.5rem;
		flex-shrink: 0;
	}

	.status.connected {
		background: #22c55e;
	}
</style>
